// Crie uma variável que receba um nome;
let name = 'name';
// Crie uma variável que receba um número;
let num = 10;
// Crie uma variável com o ano atual e subtraia pelo número que você guardou;
let yearMinusNumber = 2022 - num;
// Agora mostre no console o resultado da soma das duas variáveis guardadas anteriormente;
console.log(yearMinusNumber + num);
//Mostre no console a mensagem "Estou mexendo no console.log";
console.log('Estou mexendo no console.log');
// Crie uma variável chamada “quartaFeira” e atribua à ela o valor booleano que representa verdadeiro ou falso e mostre a saída no console;
let quartaFeira = false;
// Exiba no console o tipo de dado da váriavel quartaFeira;
console.log(typeof quartaFeira);